name: Artifact Demo

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  artifact_demo_job:
    runs-on: ubuntu-latest
    name: Artifact Demo
    steps:
      - uses: actions/checkout@v4
      - name: Generazione artefatto
        run: |
          cd ${{ github.workspace }}          
          mkdir ${{ github.workspace }}/artifact/
          echo "Artefatto di esempio" > ./artifact/artifact1.txt
          echo "Un altro artefatto di esempio" > ./artifact/artifact2.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}/artifact/
          retention-days: 1
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: downloaded_artifacts
      - name: Mostra il contenuto dell'artefatto
        run: |
          cd ${{ github.workspace }}/downloaded_artifacts
          ls -al

