name: Artifact Demo

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  artifact_demo_job:
    runs-on: ubuntu-latest
    name: Artifact Demo
    steps:
      - uses: actions/checkout@v4
      - name: Generazione artefatto
        run: |
          cd ${{ github.workspace }}          
          echo "Artefatto di esempio" > artifact.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifact.txt    
