name: Call app

on: [workflow_dispatch]

permissions:
  contents: write
  
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "GitDemo,action-demo"
      - uses: actions/checkout@v4
        with:
          repository: francesco-arca/action-demo          
          token: ${{ steps.app-token.outputs.token }}
          path: ./.github/actions/action-demo/
      - name: Run my action
        id: prova
        uses: ./.github/actions/action-demo/hello-world
        with:
          who-to-greet: 'Pinco Pallino'
      - name: Print value
        run: echo ${{ steps.prova.outputs.random-number }}
      - name: Prova Scrittura File
        run: |
          mkdir ${{ github.workspace }}/artifact/
          echo "Hello, GitHub!" > ${{ github.workspace }}/artifact/hello.txt    
          git config --global init.defaultBranch main
          git config --global user.name "Francesco Arca"
          git config --global user.email "99740491+francesco-arca@users.noreply.github.com"                    
          git init
          git remote set-url origin https://francesco-arca:${{ secrets.token }@github.com/francesco-arca/GitDemo.git
          git add ${{ github.workspace }}/artifact/hello.txt
          git commit -am "Testing Commit From Action"          
          git push origin main
