name: Calling reusable action

on: [workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    outputs:
      random: ${{ steps.prova.outputs.random-number }}
    steps:
      - uses: actions/checkout@v4
      - id: prova
        uses: ./.github/actions/hello-world
        with:
          who-to-greet: 'Pinco Pallino'
      - id: random
        run: echo random-number=%RANDOM%
        shell: cmd
        env:
          RANDOM_NUMBER: ${{ steps.prova.outputs.random-number }}
  return_random_number:
    runs-on: ubuntu-latest
    needs: hello_world_job
    steps:
      - name: Riepilogo   
        run: |
          echo "Riepilogo" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # Inserisco una linea vuota
          echo "- Il valore random generato è: " ${{ needs.hello_world_job.outputs.random }} >> $GITHUB_STEP_SUMMARY
