name: Call reusable workflow

on: [workflow_dispatch]

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      parametro: "Demo1"
    secrets:
      envPAT: ${{ secrets.PAT_REPO }}
