name: Permission Demo

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  permission_demo_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - name: Dimostrazione Scrittura File
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"      
          cd ${{ github.workspace }}
          mkdir ${{ github.workspace }}/token_demo/
          echo "Hello, GitHub!" > ${{ github.workspace }}/token_demo/hello.txt          
          # Se volete vedere nel log il contenuto della cartella potete usare il comando della shell 
          # ls -al
          git add ${{ github.workspace }}/token_demo/
          git add ${{ github.workspace }}/token_demo/hello.txt
          git commit -am "Testing Commit From Action"          
          git push origin main
