name: Staging Deploy

on: [workflow_dispatch]

  workflow_dispatch:
    inputs:
      version:
        description: Versione
        default: "1.0"
        required: true
      tags:
        description: Tags
env:
  GIORNO_DELLA_SETTIMANA: Lunedì
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Versione: ${{ github.event.inputs.version }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
        echo "Giorno: $GIORNO_DELLA_SETTIMANA"
        echo ${{ vars.PROVA }}
        echo ${GITHUB_EVENT_NAME}
        
    - name: Genero lista mediante Markdown
      run: |
        echo "Titolo dell'elenco puntato" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # Inserisco una linea vuota
        echo "- Primo punto dell'elenco" >> $GITHUB_STEP_SUMMARY
        echo "- Secondo punto dell'elenco" >> $GITHUB_STEP_SUMMARY
        echo "- Terzo punto dell'elenco?" >> $GITHUB_STEP_SUMMARY
    
    

    
    
